#include<stdio.h>
#include<time.h>
#define MIN 1 /* Minimum value of the random number. */
#define MAX 100 /* Maximum value of the random number. */

/**
 * The game() function takes an argument. The argument is the estimated number.
 * The estimated number normally comes from the user. But in our scenario,
 * there is no real user. The user is the Binary Search Algorithm. This function
 * is returning a character value of status of guess. For example: the random
 * number is 34 and argument of estimated number comes 45, in this case, this
 * function is expected to return the 'l' character. What the returned
 * characters mean:
 *
 * 'l' => the random number is lower than estimated number,
 * 'u' => the random number is upper than estimated number,
 * 'c' => the estimated number is correct.
 */
char game(int estimated_number);

/**
 * The play() function is the binary search algorithm. This function uses game()
 * function and tries to find the random number. This function prints all
 * progress steps.
 */
void play();

/**
 * Generates a random number between defined MIN and MAX values on top of file.
 */
int generate_random_number();

/**
 * This global variable stores the random number generated by
 * generate_random_number() function.
 */
int random_number;

int main()
{
    srand(time(NULL));
    random_number = generate_random_number();

    printf("BSA vs. SAW. Let's Fight!\n");
    play();
}


char game(int estimated_number)
{
    if (estimated_number > random_number) return 'l';
    if (estimated_number < random_number) return 'u';
    return 'c';
}

void play()
{
    int left = MIN;
    int right = MAX;
    int middleValue, step_count = 0;
    char check = ' ';

    while(check != 'c')
    {
        step_count++;
        middleValue = left + (right - left) / 2;

        check = game(middleValue);
        printf("Round %d:\n", step_count);
        printf("\tBSA: My guess is %d.\n", middleValue);
        if (check == 'l')
        {
            printf("\tSAW: Your guess is high.\n");
            right = middleValue - 1;
        }
        else if (check == 'u')
        {
            printf("\tSAW: Your guess is low.\n");
            left = middleValue + 1;
        }
        else
        {
            printf("\tSAW: Correct guess. You saved your files!\n");
            break;
        }
    }

    printf("\n> BSA: Gotcha! The number is %d. I found it in %d trials!",
            middleValue, step_count);
}

int generate_random_number()
{
    return MIN + rand() % (MAX + 1 - MIN);
}
